### ISSUE TITLE
Errors and warnings compiling with GCC 15

### ISSUE THREAD

**Issue by rwmjones** [AFLplusplus/AFLplusplus#2292]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch

YES
 
**Describe the bug**

AFL++ has some issues compiling with GCC 15.  I will attach the full log to this bug, but some of them are:

```
In function ‘read’,
    inlined from ‘main’ at src/afl-fuzz.c:2686:7:
/usr/include/bits/unistd.h:32:10: warning: ‘__read_alias’ writing 96 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
   32 |   return __glibc_fortify (read, __nbytes, sizeof (char),
      |          ^
include/afl-fuzz.h: In function ‘main’:
include/afl-fuzz.h:212:6: note: destination object ‘colorized’ of size 1
  212 |   u8 colorized,                         /* Do not run redqueen stage again  */
      |      ^
/usr/include/bits/unistd-decl.h:29:16: note: in a call to function ‘__read_alias’ declared with attribute ‘access (write_only, 2, 3)’
   29 | extern ssize_t __REDIRECT_FORTIFY (__read_alias, (int __fd, void *__buf,
      |                ^
In function ‘read’,
    inlined from ‘main’ at src/afl-fuzz.c:2686:7:
/usr/include/bits/unistd.h:32:10: warning: ‘__read_chk’ writing 96 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
   32 |   return __glibc_fortify (read, __nbytes, sizeof (char),
      |          ^
include/afl-fuzz.h: In function ‘main’:
include/afl-fuzz.h:212:6: note: destination object ‘colorized’ of size 1
  212 |   u8 colorized,                         /* Do not run redqueen stage again  */
      |      ^
/usr/include/bits/unistd-decl.h:26:16: note: in a call to function ‘__read_chk’ declared with attribute ‘access (write_only, 2, 3)’
   26 | extern ssize_t __read_chk (int __fd, void *__buf, size_t __nbytes,
      |                ^
```

```
src/afl-showmap.c: In function ‘showmap_run_target’:
src/afl-showmap.c:635:21: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
  635 |     signal(SIGALRM, kill_child);
      |                     ^~~~~~~~~~
      |                     |
      |                     void (*)(void)
In file included from include/afl-fuzz.h:55,
                 from src/afl-showmap.c:36:
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
src/afl-showmap.c:134:13: note: ‘kill_child’ declared here
  134 | static void kill_child() {
      |             ^~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
```

**To Reproduce**
1. Compile AFL++ with GCC 15.

**Additional context**

Fedora build: https://koji.fedoraproject.org/koji/taskinfo?taskID=128912200

**Comment by rwmjones** [comment]
Can't upload the build log for some reason.  The log is here, although it might get deleted after a while:
https://kojipkgs.fedoraproject.org//work/tasks/2200/128912200/build.log

**Comment by rwmjones** [comment]
Another failed build with AFL++ 4.31c:
https://kojipkgs.fedoraproject.org//work/tasks/297/129090297/build.log

**Comment by vanhauser-thc** [comment]
fixed in dev. if I missed something (something else might fail in a different source) then please paste a build.log link.

**Comment by rwmjones** [comment]
Confirmed it works fine now, thanks.
